name: gsheets


environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:


  http:
  html:

  meta: ^1.3.0
  openapi_dart_common: ^4.1.1
#  timeline_tile:
  connector_openapi:
    git:
      url: git@github.com:open-runtime/generated_runtime.git
      path: sdk/http/dart/connector
  core_openapi:
    git:
      url: git@github.com:open-runtime/generated_runtime.git
      path: sdk/http/dart/core
  #      url: git@bitbucket.org:pi3c3s/isomorphic_openapi.git
  #      path: ./core/dart/
  string_stats: ^0.1.0
#  runtime_client:
#    git:
#      url: git@github.com:open-runtime/runtime_client.git
dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.4
  builds_openapi:
    git:
      url: git@github.com:open-runtime/generated_runtime.git
      path: ./sdk/http/dart/builds/





fonts:
  - family: RobotoMono
    fonts:
      - asset: assets/fonts/RobotoMono-Regular.ttf
          -images/piecesFD.png

    assets:
      -assets/piecesLogo.png
      -assets/dart.jpg
      -assets/PiecesFD.png